apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: mobilesecurityservices.mobile-security-service.aerogear.com
spec:
  group: mobile-security-service.aerogear.com
  names:
    kind: MobileSecurityService
    listKind: MobileSecurityServiceList
    plural: mobilesecurityservices
    singular: mobilesecurityservice
  scope: Namespaced
  subresources:
    status: {}
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
